### ISSUE TITLE
Todo & Try

### ISSUE THREAD

**Issue by dextermallo** [dextermallo/BrainCompress#1]
# Todo & Try

- [x] [SwiftyButton](https://github.com/TakeScoop/SwiftyButton)
- [x] [Share func.](https://stackoverflow.com/questions/35931946/basic-example-for-sharing-text-or-image-with-uiactivityviewcontroller-in-swift)
- [x] [Alert Transition](https://github.com/loopeer/AlertTransition)
- [x] [Collapsible table](https://github.com/jeantimex/ios-swift-collapsible-table-section-in-grouped-section) 
- [x] [Core Data sorting](https://www.itstrike.cn/Question/27e5007e-4426-4234-b517-eb5f7a96a7ea.html)
- [x] [Instruction](https://github.com/ephread/Instructions)
- [x] Collapse table via same type.
- [x] Add usage in setting page.
- [x] Evernote SDK.
- [x] Func. to clear all note.
